on: push
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout
      
    - name: ğŸ“‚ Sync files
      uses: hazemwehbi/civil_app@master
      with:
        server: ftp.max4anime.com
        username: civil@civil.hazemwhbi.com
        password: civil123456

